### ISSUE TITLE
Docs moved to learn.microsoft.com

### ISSUE THREAD

**Issue by hakenr** [jechtom/en-docs#2]
Microsoft just released the new Learn site and moved all the docs.microsoft.com content there.
Please update the extension for new URLs, such as https://learn.microsoft.com/cs-cz/dotnet/api/system.diagnostics.stopwatch
(Or let me know you are not willing to maintain the extension any more and I will create a fork with the update. Or PR.)

**Comment by jechtom** [comment]
Reproduced. I am going to fix this.
Example: https://learn.microsoft.com/cs-cz/dotnet/api/system.boolean.parse?view=net-6.0

**Comment by jechtom** [comment]
Version 1.2 is pending review by Google Chrome.

**Comment by jechtom** [comment]
Released as v1.2.
