### ISSUE TITLE
Add support.microsoft.com

### ISSUE THREAD

**Issue by bastienperez** [jechtom/en-docs#4]
Hello,
Before learn.microsoft.com, I used https://github.com/AirLancer/ffs_msdn_in_english/
I am not sure this extension will be updated so I use yours.

Any plan to add support.microsoft.com (and azure.microsoft.com for example)?

Thanks

**Comment by jechtom** [comment]
@bastienperez Thanks. Added in v1.3. I will publish it in few hours.
